--- # Open the CI at https://poggit.pmmp.io/ci/xqwtxon/BetterModeration
build-by-default: true
branches:
- main
projects:
  BetterModeration:
    path: ""
    lint: false
    icon: "BetterModeration.png"
...
