name: CI
on:
  - push
  - pull_request
jobs:
  phpstan:
    name: PHPStan Analyze
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.0.11"
    steps:
      - uses: actions/checkout@v2
      - uses: pmmp/setup-php-action@e232f72a4330a07aae8418e8aa56b64efcdda636
        with:
          php-version: ${{matrix.php-version}}
          install-path: "./dev/bin"
      - name: phpstan analyze
        run: make phpstan PHP="php -dphar.readonly=0 -dmemory_limit=256M"
